package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
* this model was generated by mybatis-generator
* table:brand
* author:null
* date:2021-23-07 14:08:27
*/
@ApiModel("Brand")
public class Brand implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:name
    * data type:VARCHAR
    */
    @ApiModelProperty("name")
    private String name;

    /**
    * column:first_letter
    * data type:VARCHAR
    */
    @ApiModelProperty("firstLetter")
    private String firstLetter;

    /**
    * column:sort
    * data type:INTEGER
    */
    @ApiModelProperty("sort")
    private Integer sort;

    /**
    * column:factory_status
    * data type:INTEGER
    */
    @ApiModelProperty("factoryStatus")
    private Integer factoryStatus;

    /**
    * column:show_status
    * data type:INTEGER
    */
    @ApiModelProperty("showStatus")
    private Integer showStatus;

    /**
    * column:product_count
    * data type:INTEGER
    */
    @ApiModelProperty("productCount")
    private Integer productCount;

    /**
    * column:product_comment_count
    * data type:INTEGER
    */
    @ApiModelProperty("productCommentCount")
    private Integer productCommentCount;

    /**
    * column:logo
    * data type:VARCHAR
    */
    @ApiModelProperty("logo")
    private String logo;

    /**
    * column:big_pic
    * data type:VARCHAR
    */
    @ApiModelProperty("bigPic")
    private String bigPic;

    /**
    * column:brand_story
    * data type:LONGVARCHAR
    */
    @ApiModelProperty("brandStory")
    private String brandStory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brand
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.id
     *
     * @return the value of brand.id
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.id
     *
     * @param id the value for brand.id
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.name
     *
     * @return the value of brand.name
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.name
     *
     * @param name the value for brand.name
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.first_letter
     *
     * @return the value of brand.first_letter
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.first_letter
     *
     * @param firstLetter the value for brand.first_letter
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.sort
     *
     * @return the value of brand.sort
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.sort
     *
     * @param sort the value for brand.sort
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.factory_status
     *
     * @return the value of brand.factory_status
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public Integer getFactoryStatus() {
        return factoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.factory_status
     *
     * @param factoryStatus the value for brand.factory_status
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setFactoryStatus(Integer factoryStatus) {
        this.factoryStatus = factoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.show_status
     *
     * @return the value of brand.show_status
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.show_status
     *
     * @param showStatus the value for brand.show_status
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.product_count
     *
     * @return the value of brand.product_count
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.product_count
     *
     * @param productCount the value for brand.product_count
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.product_comment_count
     *
     * @return the value of brand.product_comment_count
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public Integer getProductCommentCount() {
        return productCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.product_comment_count
     *
     * @param productCommentCount the value for brand.product_comment_count
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setProductCommentCount(Integer productCommentCount) {
        this.productCommentCount = productCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.logo
     *
     * @return the value of brand.logo
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.logo
     *
     * @param logo the value for brand.logo
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.big_pic
     *
     * @return the value of brand.big_pic
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public String getBigPic() {
        return bigPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.big_pic
     *
     * @param bigPic the value for brand.big_pic
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setBigPic(String bigPic) {
        this.bigPic = bigPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_story
     *
     * @return the value of brand.brand_story
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public String getBrandStory() {
        return brandStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_story
     *
     * @param brandStory the value for brand.brand_story
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    public void setBrandStory(String brandStory) {
        this.brandStory = brandStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated 2021-23-07 14:08:27
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", firstLetter=").append(firstLetter);
        sb.append(", sort=").append(sort);
        sb.append(", factoryStatus=").append(factoryStatus);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", productCount=").append(productCount);
        sb.append(", productCommentCount=").append(productCommentCount);
        sb.append(", logo=").append(logo);
        sb.append(", bigPic=").append(bigPic);
        sb.append(", brandStory=").append(brandStory);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}