package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;

/**
* this model was generated by mybatis-generator
* table:member_price
* author:null
* date:2021-19-09 22:08:17
*/
@ApiModel("MemberPrice")
public class MemberPrice implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:product_id
    * data type:BIGINT
    */
    @ApiModelProperty("productId")
    private Long productId;

    /**
    * column:member_level_id
    * data type:BIGINT
    */
    @ApiModelProperty("memberLevelId")
    private Long memberLevelId;

    /**
    * column:member_price
    * data type:DECIMAL
    */
    @ApiModelProperty("memberPrice")
    private BigDecimal memberPrice;

    /**
    * column:member_level_name
    * data type:VARCHAR
    */
    @ApiModelProperty("memberLevelName")
    private String memberLevelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_price.id
     *
     * @return the value of member_price.id
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_price.id
     *
     * @param id the value for member_price.id
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_price.product_id
     *
     * @return the value of member_price.product_id
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_price.product_id
     *
     * @param productId the value for member_price.product_id
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_price.member_level_id
     *
     * @return the value of member_price.member_level_id
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public Long getMemberLevelId() {
        return memberLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_price.member_level_id
     *
     * @param memberLevelId the value for member_price.member_level_id
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public void setMemberLevelId(Long memberLevelId) {
        this.memberLevelId = memberLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_price.member_price
     *
     * @return the value of member_price.member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public BigDecimal getMemberPrice() {
        return memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_price.member_price
     *
     * @param memberPrice the value for member_price.member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public void setMemberPrice(BigDecimal memberPrice) {
        this.memberPrice = memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_price.member_level_name
     *
     * @return the value of member_price.member_level_name
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public String getMemberLevelName() {
        return memberLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_price.member_level_name
     *
     * @param memberLevelName the value for member_price.member_level_name
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    public void setMemberLevelName(String memberLevelName) {
        this.memberLevelName = memberLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", memberLevelId=").append(memberLevelId);
        sb.append(", memberPrice=").append(memberPrice);
        sb.append(", memberLevelName=").append(memberLevelName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}