package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;

/**
* this model was generated by mybatis-generator
* table:order_item
* author:null
* date:2021-07-25 20:08:46
*/
@ApiModel("OrderItem")
public class OrderItem implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:order_id
    * data type:BIGINT
    */
    @ApiModelProperty("orderId")
    private Long orderId;

    /**
    * column:order_sn
    * data type:VARCHAR
    */
    @ApiModelProperty("orderSn")
    private String orderSn;

    /**
    * column:product_id
    * data type:BIGINT
    */
    @ApiModelProperty("productId")
    private Long productId;

    /**
    * column:product_pic
    * data type:VARCHAR
    */
    @ApiModelProperty("productPic")
    private String productPic;

    /**
    * column:product_name
    * data type:VARCHAR
    */
    @ApiModelProperty("productName")
    private String productName;

    /**
    * column:product_brand
    * data type:VARCHAR
    */
    @ApiModelProperty("productBrand")
    private String productBrand;

    /**
    * column:product_sn
    * data type:VARCHAR
    */
    @ApiModelProperty("productSn")
    private String productSn;

    /**
    * column:product_price
    * data type:DECIMAL
    */
    @ApiModelProperty("productPrice")
    private BigDecimal productPrice;

    /**
    * column:product_quantity
    * data type:INTEGER
    */
    @ApiModelProperty("productQuantity")
    private Integer productQuantity;

    /**
    * column:product_sku_id
    * data type:BIGINT
    */
    @ApiModelProperty("productSkuId")
    private Long productSkuId;

    /**
    * column:product_sku_code
    * data type:VARCHAR
    */
    @ApiModelProperty("productSkuCode")
    private String productSkuCode;

    /**
    * column:product_category_id
    * data type:BIGINT
    */
    @ApiModelProperty("productCategoryId")
    private Long productCategoryId;

    /**
    * column:sp1
    * data type:VARCHAR
    */
    @ApiModelProperty("sp1")
    private String sp1;

    /**
    * column:sp2
    * data type:VARCHAR
    */
    @ApiModelProperty("sp2")
    private String sp2;

    /**
    * column:sp3
    * data type:VARCHAR
    */
    @ApiModelProperty("sp3")
    private String sp3;

    /**
    * column:promotion_name
    * data type:VARCHAR
    */
    @ApiModelProperty("promotionName")
    private String promotionName;

    /**
    * column:promotion_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("promotionAmount")
    private BigDecimal promotionAmount;

    /**
    * column:coupon_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("couponAmount")
    private BigDecimal couponAmount;

    /**
    * column:integration_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("integrationAmount")
    private BigDecimal integrationAmount;

    /**
    * column:real_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("realAmount")
    private BigDecimal realAmount;

    /**
    * column:gift_integration
    * data type:INTEGER
    */
    @ApiModelProperty("giftIntegration")
    private Integer giftIntegration;

    /**
    * column:gift_growth
    * data type:INTEGER
    */
    @ApiModelProperty("giftGrowth")
    private Integer giftGrowth;

    /**
    * column:product_attr
    * data type:VARCHAR
    */
    @ApiModelProperty("productAttr")
    private String productAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_item
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.id
     *
     * @return the value of order_item.id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.id
     *
     * @param id the value for order_item.id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_id
     *
     * @return the value of order_item.order_id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_id
     *
     * @param orderId the value for order_item.order_id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_sn
     *
     * @return the value of order_item.order_sn
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_sn
     *
     * @param orderSn the value for order_item.order_sn
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_id
     *
     * @return the value of order_item.product_id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_id
     *
     * @param productId the value for order_item.product_id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_pic
     *
     * @return the value of order_item.product_pic
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getProductPic() {
        return productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_pic
     *
     * @param productPic the value for order_item.product_pic
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductPic(String productPic) {
        this.productPic = productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_name
     *
     * @return the value of order_item.product_name
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_name
     *
     * @param productName the value for order_item.product_name
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_brand
     *
     * @return the value of order_item.product_brand
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_brand
     *
     * @param productBrand the value for order_item.product_brand
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_sn
     *
     * @return the value of order_item.product_sn
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_sn
     *
     * @param productSn the value for order_item.product_sn
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_price
     *
     * @return the value of order_item.product_price
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_price
     *
     * @param productPrice the value for order_item.product_price
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_quantity
     *
     * @return the value of order_item.product_quantity
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public Integer getProductQuantity() {
        return productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_quantity
     *
     * @param productQuantity the value for order_item.product_quantity
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_sku_id
     *
     * @return the value of order_item.product_sku_id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public Long getProductSkuId() {
        return productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_sku_id
     *
     * @param productSkuId the value for order_item.product_sku_id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductSkuId(Long productSkuId) {
        this.productSkuId = productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_sku_code
     *
     * @return the value of order_item.product_sku_code
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getProductSkuCode() {
        return productSkuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_sku_code
     *
     * @param productSkuCode the value for order_item.product_sku_code
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductSkuCode(String productSkuCode) {
        this.productSkuCode = productSkuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_category_id
     *
     * @return the value of order_item.product_category_id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_category_id
     *
     * @param productCategoryId the value for order_item.product_category_id
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sp1
     *
     * @return the value of order_item.sp1
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getSp1() {
        return sp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sp1
     *
     * @param sp1 the value for order_item.sp1
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setSp1(String sp1) {
        this.sp1 = sp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sp2
     *
     * @return the value of order_item.sp2
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getSp2() {
        return sp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sp2
     *
     * @param sp2 the value for order_item.sp2
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setSp2(String sp2) {
        this.sp2 = sp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sp3
     *
     * @return the value of order_item.sp3
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getSp3() {
        return sp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sp3
     *
     * @param sp3 the value for order_item.sp3
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setSp3(String sp3) {
        this.sp3 = sp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.promotion_name
     *
     * @return the value of order_item.promotion_name
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getPromotionName() {
        return promotionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.promotion_name
     *
     * @param promotionName the value for order_item.promotion_name
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setPromotionName(String promotionName) {
        this.promotionName = promotionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.promotion_amount
     *
     * @return the value of order_item.promotion_amount
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public BigDecimal getPromotionAmount() {
        return promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.promotion_amount
     *
     * @param promotionAmount the value for order_item.promotion_amount
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setPromotionAmount(BigDecimal promotionAmount) {
        this.promotionAmount = promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.coupon_amount
     *
     * @return the value of order_item.coupon_amount
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public BigDecimal getCouponAmount() {
        return couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.coupon_amount
     *
     * @param couponAmount the value for order_item.coupon_amount
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setCouponAmount(BigDecimal couponAmount) {
        this.couponAmount = couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.integration_amount
     *
     * @return the value of order_item.integration_amount
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public BigDecimal getIntegrationAmount() {
        return integrationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.integration_amount
     *
     * @param integrationAmount the value for order_item.integration_amount
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setIntegrationAmount(BigDecimal integrationAmount) {
        this.integrationAmount = integrationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.real_amount
     *
     * @return the value of order_item.real_amount
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public BigDecimal getRealAmount() {
        return realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.real_amount
     *
     * @param realAmount the value for order_item.real_amount
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setRealAmount(BigDecimal realAmount) {
        this.realAmount = realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.gift_integration
     *
     * @return the value of order_item.gift_integration
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public Integer getGiftIntegration() {
        return giftIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.gift_integration
     *
     * @param giftIntegration the value for order_item.gift_integration
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setGiftIntegration(Integer giftIntegration) {
        this.giftIntegration = giftIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.gift_growth
     *
     * @return the value of order_item.gift_growth
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public Integer getGiftGrowth() {
        return giftGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.gift_growth
     *
     * @param giftGrowth the value for order_item.gift_growth
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setGiftGrowth(Integer giftGrowth) {
        this.giftGrowth = giftGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_attr
     *
     * @return the value of order_item.product_attr
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public String getProductAttr() {
        return productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_attr
     *
     * @param productAttr the value for order_item.product_attr
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    public void setProductAttr(String productAttr) {
        this.productAttr = productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated 2021-07-25 20:08:46
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", productId=").append(productId);
        sb.append(", productPic=").append(productPic);
        sb.append(", productName=").append(productName);
        sb.append(", productBrand=").append(productBrand);
        sb.append(", productSn=").append(productSn);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", productQuantity=").append(productQuantity);
        sb.append(", productSkuId=").append(productSkuId);
        sb.append(", productSkuCode=").append(productSkuCode);
        sb.append(", productCategoryId=").append(productCategoryId);
        sb.append(", sp1=").append(sp1);
        sb.append(", sp2=").append(sp2);
        sb.append(", sp3=").append(sp3);
        sb.append(", promotionName=").append(promotionName);
        sb.append(", promotionAmount=").append(promotionAmount);
        sb.append(", couponAmount=").append(couponAmount);
        sb.append(", integrationAmount=").append(integrationAmount);
        sb.append(", realAmount=").append(realAmount);
        sb.append(", giftIntegration=").append(giftIntegration);
        sb.append(", giftGrowth=").append(giftGrowth);
        sb.append(", productAttr=").append(productAttr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}