package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
* this model was generated by mybatis-generator
* table:orders
* author:null
* date:2021-38-23 15:08:46
*/
@ApiModel("Order")
public class Order implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:member_id
    * data type:BIGINT
    */
    @ApiModelProperty("memberId")
    private Long memberId;

    /**
    * column:coupon_id
    * data type:BIGINT
    */
    @ApiModelProperty("couponId")
    private Long couponId;

    /**
    * column:order_sn
    * data type:VARCHAR
    */
    @ApiModelProperty("orderSn")
    private String orderSn;

    /**
    * column:create_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("createTime")
    private Date createTime;

    /**
    * column:member_username
    * data type:VARCHAR
    */
    @ApiModelProperty("memberUsername")
    private String memberUsername;

    /**
    * column:total_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("totalAmount")
    private BigDecimal totalAmount;

    /**
    * column:pay_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("payAmount")
    private BigDecimal payAmount;

    /**
    * column:freight_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("freightAmount")
    private BigDecimal freightAmount;

    /**
    * column:promotion_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("promotionAmount")
    private BigDecimal promotionAmount;

    /**
    * column:integration_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("integrationAmount")
    private BigDecimal integrationAmount;

    /**
    * column:coupon_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("couponAmount")
    private BigDecimal couponAmount;

    /**
    * column:discount_amount
    * data type:DECIMAL
    */
    @ApiModelProperty("discountAmount")
    private BigDecimal discountAmount;

    /**
    * column:pay_type
    * data type:INTEGER
    */
    @ApiModelProperty("payType")
    private Integer payType;

    /**
    * column:source_type
    * data type:INTEGER
    */
    @ApiModelProperty("sourceType")
    private Integer sourceType;

    /**
    * column:status
    * data type:INTEGER
    */
    @ApiModelProperty("status")
    private Integer status;

    /**
    * column:order_type
    * data type:INTEGER
    */
    @ApiModelProperty("orderType")
    private Integer orderType;

    /**
    * column:delivery_company
    * data type:VARCHAR
    */
    @ApiModelProperty("deliveryCompany")
    private String deliveryCompany;

    /**
    * column:delivery_sn
    * data type:VARCHAR
    */
    @ApiModelProperty("deliverySn")
    private String deliverySn;

    /**
    * column:auto_confirm_day
    * data type:INTEGER
    */
    @ApiModelProperty("autoConfirmDay")
    private Integer autoConfirmDay;

    /**
    * column:integration
    * data type:INTEGER
    */
    @ApiModelProperty("integration")
    private Integer integration;

    /**
    * column:growth
    * data type:INTEGER
    */
    @ApiModelProperty("growth")
    private Integer growth;

    /**
    * column:promotion_info
    * data type:VARCHAR
    */
    @ApiModelProperty("promotionInfo")
    private String promotionInfo;

    /**
    * column:bill_type
    * data type:INTEGER
    */
    @ApiModelProperty("billType")
    private Integer billType;

    /**
    * column:bill_header
    * data type:VARCHAR
    */
    @ApiModelProperty("billHeader")
    private String billHeader;

    /**
    * column:bill_content
    * data type:VARCHAR
    */
    @ApiModelProperty("billContent")
    private String billContent;

    /**
    * column:bill_receiver_phone
    * data type:VARCHAR
    */
    @ApiModelProperty("billReceiverPhone")
    private String billReceiverPhone;

    /**
    * column:bill_receiver_email
    * data type:VARCHAR
    */
    @ApiModelProperty("billReceiverEmail")
    private String billReceiverEmail;

    /**
    * column:receiver_name
    * data type:VARCHAR
    */
    @ApiModelProperty("receiverName")
    private String receiverName;

    /**
    * column:receiver_phone
    * data type:VARCHAR
    */
    @ApiModelProperty("receiverPhone")
    private String receiverPhone;

    /**
    * column:receiver_post_code
    * data type:VARCHAR
    */
    @ApiModelProperty("receiverPostCode")
    private String receiverPostCode;

    /**
    * column:receiver_province
    * data type:VARCHAR
    */
    @ApiModelProperty("receiverProvince")
    private String receiverProvince;

    /**
    * column:receiver_city
    * data type:VARCHAR
    */
    @ApiModelProperty("receiverCity")
    private String receiverCity;

    /**
    * column:receiver_region
    * data type:VARCHAR
    */
    @ApiModelProperty("receiverRegion")
    private String receiverRegion;

    /**
    * column:receiver_detail_address
    * data type:VARCHAR
    */
    @ApiModelProperty("receiverDetailAddress")
    private String receiverDetailAddress;

    /**
    * column:note
    * data type:VARCHAR
    */
    @ApiModelProperty("note")
    private String note;

    /**
    * column:confirm_status
    * data type:INTEGER
    */
    @ApiModelProperty("confirmStatus")
    private Integer confirmStatus;

    /**
    * column:delete_status
    * data type:INTEGER
    */
    @ApiModelProperty("deleteStatus")
    private Integer deleteStatus;

    /**
    * column:use_integration
    * data type:INTEGER
    */
    @ApiModelProperty("useIntegration")
    private Integer useIntegration;

    /**
    * column:payment_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("paymentTime")
    private Date paymentTime;

    /**
    * column:delivery_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("deliveryTime")
    private Date deliveryTime;

    /**
    * column:receive_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("receiveTime")
    private Date receiveTime;

    /**
    * column:comment_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("commentTime")
    private Date commentTime;

    /**
    * column:modify_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("modifyTime")
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.member_id
     *
     * @return the value of orders.member_id
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.member_id
     *
     * @param memberId the value for orders.member_id
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.coupon_id
     *
     * @return the value of orders.coupon_id
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.coupon_id
     *
     * @param couponId the value for orders.coupon_id
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_sn
     *
     * @return the value of orders.order_sn
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_sn
     *
     * @param orderSn the value for orders.order_sn
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.member_username
     *
     * @return the value of orders.member_username
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getMemberUsername() {
        return memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.member_username
     *
     * @param memberUsername the value for orders.member_username
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setMemberUsername(String memberUsername) {
        this.memberUsername = memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_amount
     *
     * @return the value of orders.total_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_amount
     *
     * @param totalAmount the value for orders.total_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_amount
     *
     * @return the value of orders.pay_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_amount
     *
     * @param payAmount the value for orders.pay_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.freight_amount
     *
     * @return the value of orders.freight_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public BigDecimal getFreightAmount() {
        return freightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.freight_amount
     *
     * @param freightAmount the value for orders.freight_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setFreightAmount(BigDecimal freightAmount) {
        this.freightAmount = freightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.promotion_amount
     *
     * @return the value of orders.promotion_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public BigDecimal getPromotionAmount() {
        return promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.promotion_amount
     *
     * @param promotionAmount the value for orders.promotion_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setPromotionAmount(BigDecimal promotionAmount) {
        this.promotionAmount = promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.integration_amount
     *
     * @return the value of orders.integration_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public BigDecimal getIntegrationAmount() {
        return integrationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.integration_amount
     *
     * @param integrationAmount the value for orders.integration_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setIntegrationAmount(BigDecimal integrationAmount) {
        this.integrationAmount = integrationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.coupon_amount
     *
     * @return the value of orders.coupon_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public BigDecimal getCouponAmount() {
        return couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.coupon_amount
     *
     * @param couponAmount the value for orders.coupon_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setCouponAmount(BigDecimal couponAmount) {
        this.couponAmount = couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.discount_amount
     *
     * @return the value of orders.discount_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.discount_amount
     *
     * @param discountAmount the value for orders.discount_amount
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_type
     *
     * @return the value of orders.pay_type
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_type
     *
     * @param payType the value for orders.pay_type
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.source_type
     *
     * @return the value of orders.source_type
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.source_type
     *
     * @param sourceType the value for orders.source_type
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_type
     *
     * @return the value of orders.order_type
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_type
     *
     * @param orderType the value for orders.order_type
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delivery_company
     *
     * @return the value of orders.delivery_company
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delivery_company
     *
     * @param deliveryCompany the value for orders.delivery_company
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delivery_sn
     *
     * @return the value of orders.delivery_sn
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getDeliverySn() {
        return deliverySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delivery_sn
     *
     * @param deliverySn the value for orders.delivery_sn
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setDeliverySn(String deliverySn) {
        this.deliverySn = deliverySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.auto_confirm_day
     *
     * @return the value of orders.auto_confirm_day
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getAutoConfirmDay() {
        return autoConfirmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.auto_confirm_day
     *
     * @param autoConfirmDay the value for orders.auto_confirm_day
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setAutoConfirmDay(Integer autoConfirmDay) {
        this.autoConfirmDay = autoConfirmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.integration
     *
     * @return the value of orders.integration
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.integration
     *
     * @param integration the value for orders.integration
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setIntegration(Integer integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.growth
     *
     * @return the value of orders.growth
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getGrowth() {
        return growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.growth
     *
     * @param growth the value for orders.growth
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setGrowth(Integer growth) {
        this.growth = growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.promotion_info
     *
     * @return the value of orders.promotion_info
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getPromotionInfo() {
        return promotionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.promotion_info
     *
     * @param promotionInfo the value for orders.promotion_info
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setPromotionInfo(String promotionInfo) {
        this.promotionInfo = promotionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bill_type
     *
     * @return the value of orders.bill_type
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bill_type
     *
     * @param billType the value for orders.bill_type
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bill_header
     *
     * @return the value of orders.bill_header
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getBillHeader() {
        return billHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bill_header
     *
     * @param billHeader the value for orders.bill_header
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setBillHeader(String billHeader) {
        this.billHeader = billHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bill_content
     *
     * @return the value of orders.bill_content
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getBillContent() {
        return billContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bill_content
     *
     * @param billContent the value for orders.bill_content
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setBillContent(String billContent) {
        this.billContent = billContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bill_receiver_phone
     *
     * @return the value of orders.bill_receiver_phone
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getBillReceiverPhone() {
        return billReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bill_receiver_phone
     *
     * @param billReceiverPhone the value for orders.bill_receiver_phone
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setBillReceiverPhone(String billReceiverPhone) {
        this.billReceiverPhone = billReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bill_receiver_email
     *
     * @return the value of orders.bill_receiver_email
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getBillReceiverEmail() {
        return billReceiverEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bill_receiver_email
     *
     * @param billReceiverEmail the value for orders.bill_receiver_email
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setBillReceiverEmail(String billReceiverEmail) {
        this.billReceiverEmail = billReceiverEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_name
     *
     * @return the value of orders.receiver_name
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_name
     *
     * @param receiverName the value for orders.receiver_name
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_phone
     *
     * @return the value of orders.receiver_phone
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_phone
     *
     * @param receiverPhone the value for orders.receiver_phone
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_post_code
     *
     * @return the value of orders.receiver_post_code
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getReceiverPostCode() {
        return receiverPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_post_code
     *
     * @param receiverPostCode the value for orders.receiver_post_code
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setReceiverPostCode(String receiverPostCode) {
        this.receiverPostCode = receiverPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_province
     *
     * @return the value of orders.receiver_province
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_province
     *
     * @param receiverProvince the value for orders.receiver_province
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_city
     *
     * @return the value of orders.receiver_city
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_city
     *
     * @param receiverCity the value for orders.receiver_city
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_region
     *
     * @return the value of orders.receiver_region
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getReceiverRegion() {
        return receiverRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_region
     *
     * @param receiverRegion the value for orders.receiver_region
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setReceiverRegion(String receiverRegion) {
        this.receiverRegion = receiverRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_detail_address
     *
     * @return the value of orders.receiver_detail_address
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getReceiverDetailAddress() {
        return receiverDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_detail_address
     *
     * @param receiverDetailAddress the value for orders.receiver_detail_address
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setReceiverDetailAddress(String receiverDetailAddress) {
        this.receiverDetailAddress = receiverDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.note
     *
     * @return the value of orders.note
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.note
     *
     * @param note the value for orders.note
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.confirm_status
     *
     * @return the value of orders.confirm_status
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getConfirmStatus() {
        return confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.confirm_status
     *
     * @param confirmStatus the value for orders.confirm_status
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setConfirmStatus(Integer confirmStatus) {
        this.confirmStatus = confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delete_status
     *
     * @return the value of orders.delete_status
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delete_status
     *
     * @param deleteStatus the value for orders.delete_status
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.use_integration
     *
     * @return the value of orders.use_integration
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Integer getUseIntegration() {
        return useIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.use_integration
     *
     * @param useIntegration the value for orders.use_integration
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setUseIntegration(Integer useIntegration) {
        this.useIntegration = useIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payment_time
     *
     * @return the value of orders.payment_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payment_time
     *
     * @param paymentTime the value for orders.payment_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delivery_time
     *
     * @return the value of orders.delivery_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delivery_time
     *
     * @param deliveryTime the value for orders.delivery_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receive_time
     *
     * @return the value of orders.receive_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receive_time
     *
     * @param receiveTime the value for orders.receive_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.comment_time
     *
     * @return the value of orders.comment_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.comment_time
     *
     * @param commentTime the value for orders.comment_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.modify_time
     *
     * @return the value of orders.modify_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.modify_time
     *
     * @param modifyTime the value for orders.modify_time
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-38-23 15:08:46
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", couponId=").append(couponId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", createTime=").append(createTime);
        sb.append(", memberUsername=").append(memberUsername);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", freightAmount=").append(freightAmount);
        sb.append(", promotionAmount=").append(promotionAmount);
        sb.append(", integrationAmount=").append(integrationAmount);
        sb.append(", couponAmount=").append(couponAmount);
        sb.append(", discountAmount=").append(discountAmount);
        sb.append(", payType=").append(payType);
        sb.append(", sourceType=").append(sourceType);
        sb.append(", status=").append(status);
        sb.append(", orderType=").append(orderType);
        sb.append(", deliveryCompany=").append(deliveryCompany);
        sb.append(", deliverySn=").append(deliverySn);
        sb.append(", autoConfirmDay=").append(autoConfirmDay);
        sb.append(", integration=").append(integration);
        sb.append(", growth=").append(growth);
        sb.append(", promotionInfo=").append(promotionInfo);
        sb.append(", billType=").append(billType);
        sb.append(", billHeader=").append(billHeader);
        sb.append(", billContent=").append(billContent);
        sb.append(", billReceiverPhone=").append(billReceiverPhone);
        sb.append(", billReceiverEmail=").append(billReceiverEmail);
        sb.append(", receiverName=").append(receiverName);
        sb.append(", receiverPhone=").append(receiverPhone);
        sb.append(", receiverPostCode=").append(receiverPostCode);
        sb.append(", receiverProvince=").append(receiverProvince);
        sb.append(", receiverCity=").append(receiverCity);
        sb.append(", receiverRegion=").append(receiverRegion);
        sb.append(", receiverDetailAddress=").append(receiverDetailAddress);
        sb.append(", note=").append(note);
        sb.append(", confirmStatus=").append(confirmStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", useIntegration=").append(useIntegration);
        sb.append(", paymentTime=").append(paymentTime);
        sb.append(", deliveryTime=").append(deliveryTime);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", commentTime=").append(commentTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}