package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
* this model was generated by mybatis-generator
* table:order_operate_history
* author:null
* date:2021-08-25 20:08:34
*/
@ApiModel("OrderOperateHistory")
public class OrderOperateHistory implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:order_id
    * data type:BIGINT
    */
    @ApiModelProperty("orderId")
    private Long orderId;

    /**
    * column:operate_man
    * data type:VARCHAR
    */
    @ApiModelProperty("operateMan")
    private String operateMan;

    /**
    * column:create_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("createTime")
    private Date createTime;

    /**
    * column:order_status
    * data type:INTEGER
    */
    @ApiModelProperty("orderStatus")
    private Integer orderStatus;

    /**
    * column:note
    * data type:VARCHAR
    */
    @ApiModelProperty("note")
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operate_history.id
     *
     * @return the value of order_operate_history.id
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operate_history.id
     *
     * @param id the value for order_operate_history.id
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operate_history.order_id
     *
     * @return the value of order_operate_history.order_id
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operate_history.order_id
     *
     * @param orderId the value for order_operate_history.order_id
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operate_history.operate_man
     *
     * @return the value of order_operate_history.operate_man
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public String getOperateMan() {
        return operateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operate_history.operate_man
     *
     * @param operateMan the value for order_operate_history.operate_man
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public void setOperateMan(String operateMan) {
        this.operateMan = operateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operate_history.create_time
     *
     * @return the value of order_operate_history.create_time
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operate_history.create_time
     *
     * @param createTime the value for order_operate_history.create_time
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operate_history.order_status
     *
     * @return the value of order_operate_history.order_status
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operate_history.order_status
     *
     * @param orderStatus the value for order_operate_history.order_status
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_operate_history.note
     *
     * @return the value of order_operate_history.note
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_operate_history.note
     *
     * @param note the value for order_operate_history.note
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", operateMan=").append(operateMan);
        sb.append(", createTime=").append(createTime);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}