package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;

/**
* this model was generated by mybatis-generator
* table:product_full_reduction
* author:null
* date:2021-11-09 19:08:05
*/
@ApiModel("ProductFullReduction")
public class ProductFullReduction implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:product_id
    * data type:BIGINT
    */
    @ApiModelProperty("productId")
    private Long productId;

    /**
    * column:full_price
    * data type:DECIMAL
    */
    @ApiModelProperty("fullPrice")
    private BigDecimal fullPrice;

    /**
    * column:reduce_price
    * data type:DECIMAL
    */
    @ApiModelProperty("reducePrice")
    private BigDecimal reducePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_full_reduction
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_full_reduction.id
     *
     * @return the value of product_full_reduction.id
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_full_reduction.id
     *
     * @param id the value for product_full_reduction.id
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_full_reduction.product_id
     *
     * @return the value of product_full_reduction.product_id
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_full_reduction.product_id
     *
     * @param productId the value for product_full_reduction.product_id
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_full_reduction.full_price
     *
     * @return the value of product_full_reduction.full_price
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    public BigDecimal getFullPrice() {
        return fullPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_full_reduction.full_price
     *
     * @param fullPrice the value for product_full_reduction.full_price
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    public void setFullPrice(BigDecimal fullPrice) {
        this.fullPrice = fullPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_full_reduction.reduce_price
     *
     * @return the value of product_full_reduction.reduce_price
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    public BigDecimal getReducePrice() {
        return reducePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_full_reduction.reduce_price
     *
     * @param reducePrice the value for product_full_reduction.reduce_price
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    public void setReducePrice(BigDecimal reducePrice) {
        this.reducePrice = reducePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_full_reduction
     *
     * @mbg.generated 2021-11-09 19:08:05
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", fullPrice=").append(fullPrice);
        sb.append(", reducePrice=").append(reducePrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}