package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
* this model was generated by mybatis-generator
* table:product_attribute_value
* author:null
* date:2021-10-09 19:08:04
*/
@ApiModel("ProductAttributeValue")
public class ProductAttributeValue implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:product_id
    * data type:BIGINT
    */
    @ApiModelProperty("productId")
    private Long productId;

    /**
    * column:product_attribute_id
    * data type:BIGINT
    */
    @ApiModelProperty("productAttributeId")
    private Long productAttributeId;

    /**
    * column:value
    * data type:VARCHAR
    */
    @ApiModelProperty("value")
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_attribute_value
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute_value.id
     *
     * @return the value of product_attribute_value.id
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute_value.id
     *
     * @param id the value for product_attribute_value.id
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute_value.product_id
     *
     * @return the value of product_attribute_value.product_id
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute_value.product_id
     *
     * @param productId the value for product_attribute_value.product_id
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute_value.product_attribute_id
     *
     * @return the value of product_attribute_value.product_attribute_id
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    public Long getProductAttributeId() {
        return productAttributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute_value.product_attribute_id
     *
     * @param productAttributeId the value for product_attribute_value.product_attribute_id
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    public void setProductAttributeId(Long productAttributeId) {
        this.productAttributeId = productAttributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute_value.value
     *
     * @return the value of product_attribute_value.value
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute_value.value
     *
     * @param value the value for product_attribute_value.value
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_value
     *
     * @mbg.generated 2021-10-09 19:08:04
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", productAttributeId=").append(productAttributeId);
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}