package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;

/**
* this model was generated by mybatis-generator
* table:product_ladder
* author:null
* date:2021-27-10 10:08:32
*/
@ApiModel("ProductLadder")
public class ProductLadder implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:product_id
    * data type:BIGINT
    */
    @ApiModelProperty("productId")
    private Long productId;

    /**
    * column:count
    * data type:INTEGER
    */
    @ApiModelProperty("count")
    private Integer count;

    /**
    * column:discount
    * data type:DECIMAL
    */
    @ApiModelProperty("discount")
    private BigDecimal discount;

    /**
    * column:price
    * data type:DECIMAL
    */
    @ApiModelProperty("price")
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_ladder.id
     *
     * @return the value of product_ladder.id
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_ladder.id
     *
     * @param id the value for product_ladder.id
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_ladder.product_id
     *
     * @return the value of product_ladder.product_id
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_ladder.product_id
     *
     * @param productId the value for product_ladder.product_id
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_ladder.count
     *
     * @return the value of product_ladder.count
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_ladder.count
     *
     * @param count the value for product_ladder.count
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_ladder.discount
     *
     * @return the value of product_ladder.discount
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_ladder.discount
     *
     * @param discount the value for product_ladder.discount
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_ladder.price
     *
     * @return the value of product_ladder.price
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_ladder.price
     *
     * @param price the value for product_ladder.price
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", count=").append(count);
        sb.append(", discount=").append(discount);
        sb.append(", price=").append(price);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}