package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
* this model was generated by mybatis-generator
* table:product_category
* author:null
* date:2021-13-06 22:08:32
*/
@ApiModel("ProductCate")
public class ProductCate implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:parent_id
    * data type:BIGINT
    */
    @ApiModelProperty("parentId")
    private Long parentId;

    /**
    * column:name
    * data type:VARCHAR
    */
    @ApiModelProperty("name")
    private String name;

    /**
    * column:level
    * data type:INTEGER
    */
    @ApiModelProperty("level")
    private Integer level;

    /**
    * column:product_count
    * data type:INTEGER
    */
    @ApiModelProperty("productCount")
    private Integer productCount;

    /**
    * column:product_unit
    * data type:VARCHAR
    */
    @ApiModelProperty("productUnit")
    private String productUnit;

    /**
    * column:nav_status
    * data type:INTEGER
    */
    @ApiModelProperty("navStatus")
    private Integer navStatus;

    /**
    * column:show_status
    * data type:INTEGER
    */
    @ApiModelProperty("showStatus")
    private Integer showStatus;

    /**
    * column:sort
    * data type:INTEGER
    */
    @ApiModelProperty("sort")
    private Integer sort;

    /**
    * column:icon
    * data type:VARCHAR
    */
    @ApiModelProperty("icon")
    private String icon;

    /**
    * column:keywords
    * data type:VARCHAR
    */
    @ApiModelProperty("keywords")
    private String keywords;

    /**
    * column:description
    * data type:LONGVARCHAR
    */
    @ApiModelProperty("description")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.id
     *
     * @return the value of product_category.id
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.id
     *
     * @param id the value for product_category.id
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.parent_id
     *
     * @return the value of product_category.parent_id
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.parent_id
     *
     * @param parentId the value for product_category.parent_id
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.name
     *
     * @return the value of product_category.name
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.name
     *
     * @param name the value for product_category.name
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.level
     *
     * @return the value of product_category.level
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.level
     *
     * @param level the value for product_category.level
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.product_count
     *
     * @return the value of product_category.product_count
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.product_count
     *
     * @param productCount the value for product_category.product_count
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.product_unit
     *
     * @return the value of product_category.product_unit
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public String getProductUnit() {
        return productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.product_unit
     *
     * @param productUnit the value for product_category.product_unit
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setProductUnit(String productUnit) {
        this.productUnit = productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.nav_status
     *
     * @return the value of product_category.nav_status
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public Integer getNavStatus() {
        return navStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.nav_status
     *
     * @param navStatus the value for product_category.nav_status
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setNavStatus(Integer navStatus) {
        this.navStatus = navStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.show_status
     *
     * @return the value of product_category.show_status
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.show_status
     *
     * @param showStatus the value for product_category.show_status
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.sort
     *
     * @return the value of product_category.sort
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.sort
     *
     * @param sort the value for product_category.sort
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.icon
     *
     * @return the value of product_category.icon
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.icon
     *
     * @param icon the value for product_category.icon
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.keywords
     *
     * @return the value of product_category.keywords
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.keywords
     *
     * @param keywords the value for product_category.keywords
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.description
     *
     * @return the value of product_category.description
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.description
     *
     * @param description the value for product_category.description
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", name=").append(name);
        sb.append(", level=").append(level);
        sb.append(", productCount=").append(productCount);
        sb.append(", productUnit=").append(productUnit);
        sb.append(", navStatus=").append(navStatus);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", sort=").append(sort);
        sb.append(", icon=").append(icon);
        sb.append(", keywords=").append(keywords);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}