package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
* this model was generated by mybatis-generator
* table:product_attribute
* author:null
* date:2021-09-09 19:08:22
*/
@ApiModel("ProductAttribute")
public class ProductAttribute implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:product_attribute_category_id
    * data type:BIGINT
    */
    @ApiModelProperty("productAttributeCategoryId")
    private Long productAttributeCategoryId;

    /**
    * column:name
    * data type:VARCHAR
    */
    @ApiModelProperty("name")
    private String name;

    /**
    * column:select_type
    * data type:INTEGER
    */
    @ApiModelProperty("selectType")
    private Integer selectType;

    /**
    * column:input_type
    * data type:INTEGER
    */
    @ApiModelProperty("inputType")
    private Integer inputType;

    /**
    * column:input_list
    * data type:VARCHAR
    */
    @ApiModelProperty("inputList")
    private String inputList;

    /**
    * column:sort
    * data type:INTEGER
    */
    @ApiModelProperty("sort")
    private Integer sort;

    /**
    * column:filter_type
    * data type:INTEGER
    */
    @ApiModelProperty("filterType")
    private Integer filterType;

    /**
    * column:search_type
    * data type:INTEGER
    */
    @ApiModelProperty("searchType")
    private Integer searchType;

    /**
    * column:related_status
    * data type:INTEGER
    */
    @ApiModelProperty("relatedStatus")
    private Integer relatedStatus;

    /**
    * column:hand_add_status
    * data type:INTEGER
    */
    @ApiModelProperty("handAddStatus")
    private Integer handAddStatus;

    /**
    * column:type
    * data type:INTEGER
    */
    @ApiModelProperty("type")
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.id
     *
     * @return the value of product_attribute.id
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.id
     *
     * @param id the value for product_attribute.id
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.product_attribute_category_id
     *
     * @return the value of product_attribute.product_attribute_category_id
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Long getProductAttributeCategoryId() {
        return productAttributeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.product_attribute_category_id
     *
     * @param productAttributeCategoryId the value for product_attribute.product_attribute_category_id
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setProductAttributeCategoryId(Long productAttributeCategoryId) {
        this.productAttributeCategoryId = productAttributeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.name
     *
     * @return the value of product_attribute.name
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.name
     *
     * @param name the value for product_attribute.name
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.select_type
     *
     * @return the value of product_attribute.select_type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Integer getSelectType() {
        return selectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.select_type
     *
     * @param selectType the value for product_attribute.select_type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setSelectType(Integer selectType) {
        this.selectType = selectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.input_type
     *
     * @return the value of product_attribute.input_type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Integer getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.input_type
     *
     * @param inputType the value for product_attribute.input_type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setInputType(Integer inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.input_list
     *
     * @return the value of product_attribute.input_list
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public String getInputList() {
        return inputList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.input_list
     *
     * @param inputList the value for product_attribute.input_list
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setInputList(String inputList) {
        this.inputList = inputList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.sort
     *
     * @return the value of product_attribute.sort
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.sort
     *
     * @param sort the value for product_attribute.sort
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.filter_type
     *
     * @return the value of product_attribute.filter_type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Integer getFilterType() {
        return filterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.filter_type
     *
     * @param filterType the value for product_attribute.filter_type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setFilterType(Integer filterType) {
        this.filterType = filterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.search_type
     *
     * @return the value of product_attribute.search_type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Integer getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.search_type
     *
     * @param searchType the value for product_attribute.search_type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.related_status
     *
     * @return the value of product_attribute.related_status
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Integer getRelatedStatus() {
        return relatedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.related_status
     *
     * @param relatedStatus the value for product_attribute.related_status
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setRelatedStatus(Integer relatedStatus) {
        this.relatedStatus = relatedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.hand_add_status
     *
     * @return the value of product_attribute.hand_add_status
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Integer getHandAddStatus() {
        return handAddStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.hand_add_status
     *
     * @param handAddStatus the value for product_attribute.hand_add_status
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setHandAddStatus(Integer handAddStatus) {
        this.handAddStatus = handAddStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute.type
     *
     * @return the value of product_attribute.type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute.type
     *
     * @param type the value for product_attribute.type
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productAttributeCategoryId=").append(productAttributeCategoryId);
        sb.append(", name=").append(name);
        sb.append(", selectType=").append(selectType);
        sb.append(", inputType=").append(inputType);
        sb.append(", inputList=").append(inputList);
        sb.append(", sort=").append(sort);
        sb.append(", filterType=").append(filterType);
        sb.append(", searchType=").append(searchType);
        sb.append(", relatedStatus=").append(relatedStatus);
        sb.append(", handAddStatus=").append(handAddStatus);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}