package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
* this model was generated by mybatis-generator
* table:product
* author:null
* date:2021-47-06 13:08:58
*/
@ApiModel("Product")
public class Product implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:brand_id
    * data type:BIGINT
    */
    @ApiModelProperty("brandId")
    private Long brandId;

    /**
    * column:product_category_id
    * data type:BIGINT
    */
    @ApiModelProperty("productCategoryId")
    private Long productCategoryId;

    /**
    * column:feight_template_id
    * data type:BIGINT
    */
    @ApiModelProperty("feightTemplateId")
    private Long feightTemplateId;

    /**
    * column:product_attribute_category_id
    * data type:BIGINT
    */
    @ApiModelProperty("productAttributeCategoryId")
    private Long productAttributeCategoryId;

    /**
    * column:name
    * data type:VARCHAR
    */
    @ApiModelProperty("name")
    private String name;

    /**
    * column:pic
    * data type:VARCHAR
    */
    @ApiModelProperty("pic")
    private String pic;

    /**
    * column:product_sn
    * data type:VARCHAR
    */
    @ApiModelProperty("productSn")
    private String productSn;

    /**
    * column:delete_status
    * data type:INTEGER
    */
    @ApiModelProperty("deleteStatus")
    private Integer deleteStatus;

    /**
    * column:publish_status
    * data type:INTEGER
    */
    @ApiModelProperty("publishStatus")
    private Integer publishStatus;

    /**
    * column:new_status
    * data type:INTEGER
    */
    @ApiModelProperty("newStatus")
    private Integer newStatus;

    /**
    * column:recommand_status
    * data type:INTEGER
    */
    @ApiModelProperty("recommandStatus")
    private Integer recommandStatus;

    /**
    * column:verify_status
    * data type:INTEGER
    */
    @ApiModelProperty("verifyStatus")
    private Integer verifyStatus;

    /**
    * column:sort
    * data type:INTEGER
    */
    @ApiModelProperty("sort")
    private Integer sort;

    /**
    * column:sale
    * data type:INTEGER
    */
    @ApiModelProperty("sale")
    private Integer sale;

    /**
    * column:price
    * data type:DECIMAL
    */
    @ApiModelProperty("price")
    private BigDecimal price;

    /**
    * column:promotion_price
    * data type:DECIMAL
    */
    @ApiModelProperty("promotionPrice")
    private BigDecimal promotionPrice;

    /**
    * column:gift_growth
    * data type:INTEGER
    */
    @ApiModelProperty("giftGrowth")
    private Integer giftGrowth;

    /**
    * column:gift_point
    * data type:INTEGER
    */
    @ApiModelProperty("giftPoint")
    private Integer giftPoint;

    /**
    * column:use_point_limit
    * data type:INTEGER
    */
    @ApiModelProperty("usePointLimit")
    private Integer usePointLimit;

    /**
    * column:sub_title
    * data type:VARCHAR
    */
    @ApiModelProperty("subTitle")
    private String subTitle;

    /**
    * column:original_price
    * data type:DECIMAL
    */
    @ApiModelProperty("originalPrice")
    private BigDecimal originalPrice;

    /**
    * column:stock
    * data type:INTEGER
    */
    @ApiModelProperty("stock")
    private Integer stock;

    /**
    * column:low_stock
    * data type:INTEGER
    */
    @ApiModelProperty("lowStock")
    private Integer lowStock;

    /**
    * column:unit
    * data type:VARCHAR
    */
    @ApiModelProperty("unit")
    private String unit;

    /**
    * column:weight
    * data type:DECIMAL
    */
    @ApiModelProperty("weight")
    private BigDecimal weight;

    /**
    * column:preview_status
    * data type:INTEGER
    */
    @ApiModelProperty("previewStatus")
    private Integer previewStatus;

    /**
    * column:service_ids
    * data type:VARCHAR
    */
    @ApiModelProperty("serviceIds")
    private String serviceIds;

    /**
    * column:keywords
    * data type:VARCHAR
    */
    @ApiModelProperty("keywords")
    private String keywords;

    /**
    * column:note
    * data type:VARCHAR
    */
    @ApiModelProperty("note")
    private String note;

    /**
    * column:album_pics
    * data type:VARCHAR
    */
    @ApiModelProperty("albumPics")
    private String albumPics;

    /**
    * column:detail_title
    * data type:VARCHAR
    */
    @ApiModelProperty("detailTitle")
    private String detailTitle;

    /**
    * column:promotion_start_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("promotionStartTime")
    private Date promotionStartTime;

    /**
    * column:promotion_end_time
    * data type:TIMESTAMP
    */
    @ApiModelProperty("promotionEndTime")
    private Date promotionEndTime;

    /**
    * column:promotion_per_limit
    * data type:INTEGER
    */
    @ApiModelProperty("promotionPerLimit")
    private Integer promotionPerLimit;

    /**
    * column:promotion_type
    * data type:INTEGER
    */
    @ApiModelProperty("promotionType")
    private Integer promotionType;

    /**
    * column:brand_name
    * data type:VARCHAR
    */
    @ApiModelProperty("brandName")
    private String brandName;

    /**
    * column:product_category_name
    * data type:VARCHAR
    */
    @ApiModelProperty("productCategoryName")
    private String productCategoryName;

    /**
    * column:description
    * data type:LONGVARCHAR
    */
    @ApiModelProperty("description")
    private String description;

    /**
    * column:detail_desc
    * data type:LONGVARCHAR
    */
    @ApiModelProperty("detailDesc")
    private String detailDesc;

    /**
    * column:detail_html
    * data type:LONGVARCHAR
    */
    @ApiModelProperty("detailHtml")
    private String detailHtml;

    /**
    * column:detail_mobile_html
    * data type:LONGVARCHAR
    */
    @ApiModelProperty("detailMobileHtml")
    private String detailMobileHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand_id
     *
     * @return the value of product.brand_id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand_id
     *
     * @param brandId the value for product.brand_id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_category_id
     *
     * @return the value of product.product_category_id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_category_id
     *
     * @param productCategoryId the value for product.product_category_id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.feight_template_id
     *
     * @return the value of product.feight_template_id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Long getFeightTemplateId() {
        return feightTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.feight_template_id
     *
     * @param feightTemplateId the value for product.feight_template_id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setFeightTemplateId(Long feightTemplateId) {
        this.feightTemplateId = feightTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_attribute_category_id
     *
     * @return the value of product.product_attribute_category_id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Long getProductAttributeCategoryId() {
        return productAttributeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_attribute_category_id
     *
     * @param productAttributeCategoryId the value for product.product_attribute_category_id
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setProductAttributeCategoryId(Long productAttributeCategoryId) {
        this.productAttributeCategoryId = productAttributeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pic
     *
     * @return the value of product.pic
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pic
     *
     * @param pic the value for product.pic
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_sn
     *
     * @return the value of product.product_sn
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_sn
     *
     * @param productSn the value for product.product_sn
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.delete_status
     *
     * @return the value of product.delete_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.delete_status
     *
     * @param deleteStatus the value for product.delete_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.publish_status
     *
     * @return the value of product.publish_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.publish_status
     *
     * @param publishStatus the value for product.publish_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.new_status
     *
     * @return the value of product.new_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getNewStatus() {
        return newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.new_status
     *
     * @param newStatus the value for product.new_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setNewStatus(Integer newStatus) {
        this.newStatus = newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.recommand_status
     *
     * @return the value of product.recommand_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getRecommandStatus() {
        return recommandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.recommand_status
     *
     * @param recommandStatus the value for product.recommand_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setRecommandStatus(Integer recommandStatus) {
        this.recommandStatus = recommandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.verify_status
     *
     * @return the value of product.verify_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.verify_status
     *
     * @param verifyStatus the value for product.verify_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setVerifyStatus(Integer verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sort
     *
     * @return the value of product.sort
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sort
     *
     * @param sort the value for product.sort
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale
     *
     * @return the value of product.sale
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale
     *
     * @param sale the value for product.sale
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotion_price
     *
     * @return the value of product.promotion_price
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public BigDecimal getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotion_price
     *
     * @param promotionPrice the value for product.promotion_price
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPromotionPrice(BigDecimal promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gift_growth
     *
     * @return the value of product.gift_growth
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getGiftGrowth() {
        return giftGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gift_growth
     *
     * @param giftGrowth the value for product.gift_growth
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setGiftGrowth(Integer giftGrowth) {
        this.giftGrowth = giftGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gift_point
     *
     * @return the value of product.gift_point
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getGiftPoint() {
        return giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gift_point
     *
     * @param giftPoint the value for product.gift_point
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setGiftPoint(Integer giftPoint) {
        this.giftPoint = giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.use_point_limit
     *
     * @return the value of product.use_point_limit
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getUsePointLimit() {
        return usePointLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.use_point_limit
     *
     * @param usePointLimit the value for product.use_point_limit
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setUsePointLimit(Integer usePointLimit) {
        this.usePointLimit = usePointLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sub_title
     *
     * @return the value of product.sub_title
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sub_title
     *
     * @param subTitle the value for product.sub_title
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.original_price
     *
     * @return the value of product.original_price
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.original_price
     *
     * @param originalPrice the value for product.original_price
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.low_stock
     *
     * @return the value of product.low_stock
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getLowStock() {
        return lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.low_stock
     *
     * @param lowStock the value for product.low_stock
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setLowStock(Integer lowStock) {
        this.lowStock = lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.unit
     *
     * @return the value of product.unit
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.unit
     *
     * @param unit the value for product.unit
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.weight
     *
     * @return the value of product.weight
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.weight
     *
     * @param weight the value for product.weight
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.preview_status
     *
     * @return the value of product.preview_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getPreviewStatus() {
        return previewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.preview_status
     *
     * @param previewStatus the value for product.preview_status
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPreviewStatus(Integer previewStatus) {
        this.previewStatus = previewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.service_ids
     *
     * @return the value of product.service_ids
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getServiceIds() {
        return serviceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.service_ids
     *
     * @param serviceIds the value for product.service_ids
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setServiceIds(String serviceIds) {
        this.serviceIds = serviceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.keywords
     *
     * @return the value of product.keywords
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.keywords
     *
     * @param keywords the value for product.keywords
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.note
     *
     * @return the value of product.note
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.note
     *
     * @param note the value for product.note
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.album_pics
     *
     * @return the value of product.album_pics
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getAlbumPics() {
        return albumPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.album_pics
     *
     * @param albumPics the value for product.album_pics
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setAlbumPics(String albumPics) {
        this.albumPics = albumPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail_title
     *
     * @return the value of product.detail_title
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getDetailTitle() {
        return detailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail_title
     *
     * @param detailTitle the value for product.detail_title
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setDetailTitle(String detailTitle) {
        this.detailTitle = detailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotion_start_time
     *
     * @return the value of product.promotion_start_time
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Date getPromotionStartTime() {
        return promotionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotion_start_time
     *
     * @param promotionStartTime the value for product.promotion_start_time
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPromotionStartTime(Date promotionStartTime) {
        this.promotionStartTime = promotionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotion_end_time
     *
     * @return the value of product.promotion_end_time
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Date getPromotionEndTime() {
        return promotionEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotion_end_time
     *
     * @param promotionEndTime the value for product.promotion_end_time
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPromotionEndTime(Date promotionEndTime) {
        this.promotionEndTime = promotionEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotion_per_limit
     *
     * @return the value of product.promotion_per_limit
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getPromotionPerLimit() {
        return promotionPerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotion_per_limit
     *
     * @param promotionPerLimit the value for product.promotion_per_limit
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPromotionPerLimit(Integer promotionPerLimit) {
        this.promotionPerLimit = promotionPerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotion_type
     *
     * @return the value of product.promotion_type
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public Integer getPromotionType() {
        return promotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotion_type
     *
     * @param promotionType the value for product.promotion_type
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setPromotionType(Integer promotionType) {
        this.promotionType = promotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand_name
     *
     * @return the value of product.brand_name
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand_name
     *
     * @param brandName the value for product.brand_name
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_category_name
     *
     * @return the value of product.product_category_name
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getProductCategoryName() {
        return productCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_category_name
     *
     * @param productCategoryName the value for product.product_category_name
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setProductCategoryName(String productCategoryName) {
        this.productCategoryName = productCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail_desc
     *
     * @return the value of product.detail_desc
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getDetailDesc() {
        return detailDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail_desc
     *
     * @param detailDesc the value for product.detail_desc
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setDetailDesc(String detailDesc) {
        this.detailDesc = detailDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail_html
     *
     * @return the value of product.detail_html
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getDetailHtml() {
        return detailHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail_html
     *
     * @param detailHtml the value for product.detail_html
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setDetailHtml(String detailHtml) {
        this.detailHtml = detailHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail_mobile_html
     *
     * @return the value of product.detail_mobile_html
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public String getDetailMobileHtml() {
        return detailMobileHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail_mobile_html
     *
     * @param detailMobileHtml the value for product.detail_mobile_html
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    public void setDetailMobileHtml(String detailMobileHtml) {
        this.detailMobileHtml = detailMobileHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated 2021-47-06 13:08:58
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brandId=").append(brandId);
        sb.append(", productCategoryId=").append(productCategoryId);
        sb.append(", feightTemplateId=").append(feightTemplateId);
        sb.append(", productAttributeCategoryId=").append(productAttributeCategoryId);
        sb.append(", name=").append(name);
        sb.append(", pic=").append(pic);
        sb.append(", productSn=").append(productSn);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", publishStatus=").append(publishStatus);
        sb.append(", newStatus=").append(newStatus);
        sb.append(", recommandStatus=").append(recommandStatus);
        sb.append(", verifyStatus=").append(verifyStatus);
        sb.append(", sort=").append(sort);
        sb.append(", sale=").append(sale);
        sb.append(", price=").append(price);
        sb.append(", promotionPrice=").append(promotionPrice);
        sb.append(", giftGrowth=").append(giftGrowth);
        sb.append(", giftPoint=").append(giftPoint);
        sb.append(", usePointLimit=").append(usePointLimit);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", originalPrice=").append(originalPrice);
        sb.append(", stock=").append(stock);
        sb.append(", lowStock=").append(lowStock);
        sb.append(", unit=").append(unit);
        sb.append(", weight=").append(weight);
        sb.append(", previewStatus=").append(previewStatus);
        sb.append(", serviceIds=").append(serviceIds);
        sb.append(", keywords=").append(keywords);
        sb.append(", note=").append(note);
        sb.append(", albumPics=").append(albumPics);
        sb.append(", detailTitle=").append(detailTitle);
        sb.append(", promotionStartTime=").append(promotionStartTime);
        sb.append(", promotionEndTime=").append(promotionEndTime);
        sb.append(", promotionPerLimit=").append(promotionPerLimit);
        sb.append(", promotionType=").append(promotionType);
        sb.append(", brandName=").append(brandName);
        sb.append(", productCategoryName=").append(productCategoryName);
        sb.append(", description=").append(description);
        sb.append(", detailDesc=").append(detailDesc);
        sb.append(", detailHtml=").append(detailHtml);
        sb.append(", detailMobileHtml=").append(detailMobileHtml);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}