package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
* this model was generated by mybatis-generator
* table:product_attribute_category
* author:null
* date:2021-09-09 19:08:45
*/
@ApiModel("ProductAttributeCategory")
public class ProductAttributeCategory implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:name
    * data type:VARCHAR
    */
    @ApiModelProperty("name")
    private String name;

    /**
    * column:attribute_count
    * data type:INTEGER
    */
    @ApiModelProperty("attributeCount")
    private Integer attributeCount;

    /**
    * column:param_count
    * data type:INTEGER
    */
    @ApiModelProperty("paramCount")
    private Integer paramCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute_category.id
     *
     * @return the value of product_attribute_category.id
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute_category.id
     *
     * @param id the value for product_attribute_category.id
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute_category.name
     *
     * @return the value of product_attribute_category.name
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute_category.name
     *
     * @param name the value for product_attribute_category.name
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute_category.attribute_count
     *
     * @return the value of product_attribute_category.attribute_count
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    public Integer getAttributeCount() {
        return attributeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute_category.attribute_count
     *
     * @param attributeCount the value for product_attribute_category.attribute_count
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    public void setAttributeCount(Integer attributeCount) {
        this.attributeCount = attributeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_attribute_category.param_count
     *
     * @return the value of product_attribute_category.param_count
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    public Integer getParamCount() {
        return paramCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_attribute_category.param_count
     *
     * @param paramCount the value for product_attribute_category.param_count
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    public void setParamCount(Integer paramCount) {
        this.paramCount = paramCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", attributeCount=").append(attributeCount);
        sb.append(", paramCount=").append(paramCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}