package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
* this model was generated by mybatis-generator
* table:subject_product_relation
* author:null
* date:2021-28-09 19:08:32
*/
@ApiModel("SubjectProductRelation")
public class SubjectProductRelation implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:subject_id
    * data type:BIGINT
    */
    @ApiModelProperty("subjectId")
    private Long subjectId;

    /**
    * column:product_id
    * data type:BIGINT
    */
    @ApiModelProperty("productId")
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_product_relation.id
     *
     * @return the value of subject_product_relation.id
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_product_relation.id
     *
     * @param id the value for subject_product_relation.id
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_product_relation.subject_id
     *
     * @return the value of subject_product_relation.subject_id
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_product_relation.subject_id
     *
     * @param subjectId the value for subject_product_relation.subject_id
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_product_relation.product_id
     *
     * @return the value of subject_product_relation.product_id
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_product_relation.product_id
     *
     * @param productId the value for subject_product_relation.product_id
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", productId=").append(productId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}