package com.liuji.mall.mbg.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
* this model was generated by mybatis-generator
* table:subject_category
* author:null
* date:2021-48-11 15:08:56
*/
@ApiModel("SubjectCategory")
public class SubjectCategory implements Serializable {
    /**
    * column:id
    * data type:BIGINT
    */
    @ApiModelProperty("id")
    private Long id;

    /**
    * column:name
    * data type:VARCHAR
    */
    @ApiModelProperty("name")
    private String name;

    /**
    * column:icon
    * data type:VARCHAR
    */
    @ApiModelProperty("icon")
    private String icon;

    /**
    * column:subject_count
    * data type:INTEGER
    */
    @ApiModelProperty("subjectCount")
    private Integer subjectCount;

    /**
    * column:show_status
    * data type:INTEGER
    */
    @ApiModelProperty("showStatus")
    private Integer showStatus;

    /**
    * column:sort
    * data type:INTEGER
    */
    @ApiModelProperty("sort")
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.id
     *
     * @return the value of subject_category.id
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.id
     *
     * @param id the value for subject_category.id
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.name
     *
     * @return the value of subject_category.name
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.name
     *
     * @param name the value for subject_category.name
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.icon
     *
     * @return the value of subject_category.icon
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.icon
     *
     * @param icon the value for subject_category.icon
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.subject_count
     *
     * @return the value of subject_category.subject_count
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public Integer getSubjectCount() {
        return subjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.subject_count
     *
     * @param subjectCount the value for subject_category.subject_count
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public void setSubjectCount(Integer subjectCount) {
        this.subjectCount = subjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.show_status
     *
     * @return the value of subject_category.show_status
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.show_status
     *
     * @param showStatus the value for subject_category.show_status
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.sort
     *
     * @return the value of subject_category.sort
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.sort
     *
     * @param sort the value for subject_category.sort
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", icon=").append(icon);
        sb.append(", subjectCount=").append(subjectCount);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}