package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.MemberPrice;
import com.liuji.mall.mbg.model.MemberPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    long countByExample(MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    int deleteByExample(MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    int insert(MemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    int insertSelective(MemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    List<MemberPrice> selectByExample(MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    MemberPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    int updateByExampleSelective(@Param("record") MemberPrice record, @Param("example") MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    int updateByExample(@Param("record") MemberPrice record, @Param("example") MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    int updateByPrimaryKeySelective(MemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_price
     *
     * @mbg.generated 2021-19-09 22:08:17
     */
    int updateByPrimaryKey(MemberPrice record);
}