package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.OrderOperateHistory;
import com.liuji.mall.mbg.model.OrderOperateHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderOperateHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    long countByExample(OrderOperateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    int deleteByExample(OrderOperateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    int insert(OrderOperateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    int insertSelective(OrderOperateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    List<OrderOperateHistory> selectByExample(OrderOperateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    OrderOperateHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    int updateByExampleSelective(@Param("record") OrderOperateHistory record, @Param("example") OrderOperateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    int updateByExample(@Param("record") OrderOperateHistory record, @Param("example") OrderOperateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    int updateByPrimaryKeySelective(OrderOperateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_operate_history
     *
     * @mbg.generated 2021-08-25 20:08:34
     */
    int updateByPrimaryKey(OrderOperateHistory record);
}