package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.PreferenceArea;
import com.liuji.mall.mbg.model.PreferenceAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreferenceAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    long countByExample(PreferenceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int deleteByExample(PreferenceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int insert(PreferenceArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int insertSelective(PreferenceArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    List<PreferenceArea> selectByExampleWithBLOBs(PreferenceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    List<PreferenceArea> selectByExample(PreferenceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    PreferenceArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int updateByExampleSelective(@Param("record") PreferenceArea record, @Param("example") PreferenceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int updateByExampleWithBLOBs(@Param("record") PreferenceArea record, @Param("example") PreferenceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int updateByExample(@Param("record") PreferenceArea record, @Param("example") PreferenceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int updateByPrimaryKeySelective(PreferenceArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int updateByPrimaryKeyWithBLOBs(PreferenceArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area
     *
     * @mbg.generated 2021-49-11 15:08:11
     */
    int updateByPrimaryKey(PreferenceArea record);
}