package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.PreferenceAreaProductRelation;
import com.liuji.mall.mbg.model.PreferenceAreaProductRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreferenceAreaProductRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    long countByExample(PreferenceAreaProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    int deleteByExample(PreferenceAreaProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    int insert(PreferenceAreaProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    int insertSelective(PreferenceAreaProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    List<PreferenceAreaProductRelation> selectByExample(PreferenceAreaProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    PreferenceAreaProductRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    int updateByExampleSelective(@Param("record") PreferenceAreaProductRelation record, @Param("example") PreferenceAreaProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    int updateByExample(@Param("record") PreferenceAreaProductRelation record, @Param("example") PreferenceAreaProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    int updateByPrimaryKeySelective(PreferenceAreaProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_area_product_relation
     *
     * @mbg.generated 2021-31-09 19:08:20
     */
    int updateByPrimaryKey(PreferenceAreaProductRelation record);
}