package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.ProductCate;
import com.liuji.mall.mbg.model.ProductCateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductCateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    long countByExample(ProductCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int deleteByExample(ProductCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int insert(ProductCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int insertSelective(ProductCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    List<ProductCate> selectByExampleWithBLOBs(ProductCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    List<ProductCate> selectByExample(ProductCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    ProductCate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int updateByExampleSelective(@Param("record") ProductCate record, @Param("example") ProductCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int updateByExampleWithBLOBs(@Param("record") ProductCate record, @Param("example") ProductCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int updateByExample(@Param("record") ProductCate record, @Param("example") ProductCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int updateByPrimaryKeySelective(ProductCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int updateByPrimaryKeyWithBLOBs(ProductCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-13-06 22:08:32
     */
    int updateByPrimaryKey(ProductCate record);
}