package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.ProductAttribute;
import com.liuji.mall.mbg.model.ProductAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    long countByExample(ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    int deleteByExample(ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    int insert(ProductAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    int insertSelective(ProductAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    List<ProductAttribute> selectByExample(ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    ProductAttribute selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    int updateByExampleSelective(@Param("record") ProductAttribute record, @Param("example") ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    int updateByExample(@Param("record") ProductAttribute record, @Param("example") ProductAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    int updateByPrimaryKeySelective(ProductAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute
     *
     * @mbg.generated 2021-09-09 19:08:22
     */
    int updateByPrimaryKey(ProductAttribute record);
}