package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.ProductLadder;
import com.liuji.mall.mbg.model.ProductLadderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductLadderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    long countByExample(ProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    int deleteByExample(ProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    int insert(ProductLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    int insertSelective(ProductLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    List<ProductLadder> selectByExample(ProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    ProductLadder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    int updateByExampleSelective(@Param("record") ProductLadder record, @Param("example") ProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    int updateByExample(@Param("record") ProductLadder record, @Param("example") ProductLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    int updateByPrimaryKeySelective(ProductLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_ladder
     *
     * @mbg.generated 2021-27-10 10:08:32
     */
    int updateByPrimaryKey(ProductLadder record);
}