package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.ProductAttributeCategory;
import com.liuji.mall.mbg.model.ProductAttributeCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductAttributeCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    long countByExample(ProductAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    int deleteByExample(ProductAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    int insert(ProductAttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    int insertSelective(ProductAttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    List<ProductAttributeCategory> selectByExample(ProductAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    ProductAttributeCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    int updateByExampleSelective(@Param("record") ProductAttributeCategory record, @Param("example") ProductAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    int updateByExample(@Param("record") ProductAttributeCategory record, @Param("example") ProductAttributeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    int updateByPrimaryKeySelective(ProductAttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attribute_category
     *
     * @mbg.generated 2021-09-09 19:08:45
     */
    int updateByPrimaryKey(ProductAttributeCategory record);
}