package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.SkuStock;
import com.liuji.mall.mbg.model.SkuStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkuStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    long countByExample(SkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    int deleteByExample(SkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    int insert(SkuStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    int insertSelective(SkuStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    List<SkuStock> selectByExample(SkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    SkuStock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    int updateByExampleSelective(@Param("record") SkuStock record, @Param("example") SkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    int updateByExample(@Param("record") SkuStock record, @Param("example") SkuStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    int updateByPrimaryKeySelective(SkuStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_stock
     *
     * @mbg.generated 2021-11-10 21:08:10
     */
    int updateByPrimaryKey(SkuStock record);
}