package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.SubjectCategory;
import com.liuji.mall.mbg.model.SubjectCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    long countByExample(SubjectCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    int deleteByExample(SubjectCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    int insert(SubjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    int insertSelective(SubjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    List<SubjectCategory> selectByExample(SubjectCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    SubjectCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    int updateByExampleSelective(@Param("record") SubjectCategory record, @Param("example") SubjectCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    int updateByExample(@Param("record") SubjectCategory record, @Param("example") SubjectCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    int updateByPrimaryKeySelective(SubjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbg.generated 2021-48-11 15:08:56
     */
    int updateByPrimaryKey(SubjectCategory record);
}