package com.liuji.mall.mbg.mapper;

import com.liuji.mall.mbg.model.SubjectProductRelation;
import com.liuji.mall.mbg.model.SubjectProductRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectProductRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    long countByExample(SubjectProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    int deleteByExample(SubjectProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    int insert(SubjectProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    int insertSelective(SubjectProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    List<SubjectProductRelation> selectByExample(SubjectProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    SubjectProductRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    int updateByExampleSelective(@Param("record") SubjectProductRelation record, @Param("example") SubjectProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    int updateByExample(@Param("record") SubjectProductRelation record, @Param("example") SubjectProductRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    int updateByPrimaryKeySelective(SubjectProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_product_relation
     *
     * @mbg.generated 2021-28-09 19:08:32
     */
    int updateByPrimaryKey(SubjectProductRelation record);
}